const BASE = '/api/drivers'

const handleResponse = async (res) => {
  const json = await res.json()
  if (!res.ok) throw new Error(json.error || `Request failed (${res.status})`)
  return json
}

export const fetchDrivers = () =>
  fetch(BASE).then(handleResponse)

export const fetchDriver = (mongoId) =>
  fetch(`${BASE}/${mongoId}`).then(handleResponse)

// id is auto-generated by the backend; only name is required
export const createDriver = ({ name }) =>
  fetch(BASE, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ name }),
  }).then(handleResponse)

export const updateDriver = (mongoId, { id, name }) =>
  fetch(`${BASE}/${mongoId}`, {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ id, name }),
  }).then(handleResponse)

export const deleteDriver = (mongoId) =>
  fetch(`${BASE}/${mongoId}`, { method: 'DELETE' }).then(handleResponse)

// Returns all trips for a driver, each with violations populated
export const fetchDriverTrips = (mongoId) =>
  fetch(`${BASE}/${mongoId}/trips`).then(handleResponse)
